pipeline {
    agent any

    environment {
        AWS_REGION = "eu-central-1"
        AWS_CREDENTIALS = "jenkins-aws"
        BUCKET_NAME = "www-bucket-test"
        //BUCKET_ACL = "PublicRead'"

        // This can be http or https
        NEXUS_PROTOCOL = "https"
        // Where your Nexus is running
        NEXUS_URL = "nexus.n00dns.co"
        // Jenkins credential id to authenticate to Nexus OSS
        NEXUS_CREDENTIAL_ID = credentials("jenkins_nexus")

        BUILD_PATH = "home/ec2-user/workspace/react_app/build"
    }
    stages {
        stage("Download artifact") {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'jenkins_nexus', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        sh "curl -u $USERNAME:$PASSWORD -O '${NEXUS_PROTOCOL}://${NEXUS_URL}/repository/react-app/jenkins/react-app/0.0.1/react-app-0.0.1.tgz'"
                        sh "tar -xvzf react-app-0.0.1.tgz" 
                        sh "cd ${env.WORKSPACE}/${BUILD_PATH}" 
                        sh "ls -al "
                    }
                }
            }
        }  
        stage('Upload to AWS') {
              steps {
                  withAWS(region: "${AWS_REGION}",credentials:"${AWS_CREDENTIALS}") {
                  sh 'echo "Uploading content with AWS creds"'
                      s3Upload(pathStyleAccessEnabled: true, payloadSigningEnabled: true, file:"home/ec2-user/workspace/react_app/build/", bucket:"${BUCKET_NAME}", acl: 'PublicRead)
                  }
              }
         }
     }
    post {
        always {
            cleanWs()
        }
    }
}