pipeline {
     agent any

    environment {
        AWS_REGION = "eu-central-1"
        
        AWS_CREDENTIALS = "jenkins-aws"
        
        BUCKET_NAME = "www-bucket-test"
        // Repository where we will upload the artifact
        NEXUS_REPOSITORY = "${NEXUS_REPOSITORY}"
        // Jenkins credential id to authenticate to Nexus OSS
        NEXUS_CREDENTIAL_ID = "jenkins_nexus"
        // Version of package
        PACKAGE_VERSION = "${PACKAGE_VERSION}"
        ARTIFACT_VERSION = "${BUILD_NUMBER}"
    }

     stages {
         stage('Build') {
             steps {
                 sh 'echo "Hello World"'
                 sh '''
                     echo "Multiline shell steps works too"
                     ls -lah
                 '''
             }
         }      
         stage('Upload to AWS') {
              steps {
                  withAWS(region: "${AWS_REGION}",credentials:"${AWS_CREDENTIALS}") {
                  sh 'echo "Uploading content with AWS creds"'
                      s3Upload(pathStyleAccessEnabled: true, payloadSigningEnabled: true, file:'README.md', bucket:"${BUCKET_NAME}")
                  }
              }
         }
     }
}